settings:
  title: "Dannington's Infrastructure Status"
  url: 'https://status.bean.codes' # used for Slack messages
  logo: kylar2_discordgrey.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All components operational'
  notAllmonitorsOperational: 'Some services are down'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'No data recorded'
  dayInHistogramNoData: 'No data recorded'
  dayInHistogramOperational: 'No incidents recorded'
  dayInHistogramNotOperational: ' incident(s) recorded' # xx incident(s) recorded

monitors:
  - id: web
    name: Website
    description: 'My website. Self explanatory, innit?'
    url: 'https://www.bean.codes/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: cdn
    name: CDN
    description: 'The content delivery network. Important files are stored here, in addition to public screenshots.'
    url: 'https://cdn.bean.codes/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: ci # unique identifier
    name: GitLab CI
    description: 'CI, powered by GitLab. Used to test projects and random things, in addition to other things used privately.' # default=empty
    url: 'https://ci.bean.codes/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: ptero
    name: Pterodactyl
    description: 'The panel used for managing services like the CDN or Hastebin. Powered by Pterodactyl.'
    url: 'https://dedi.bean.codes'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: haste
    name: Hastebin
    description: 'A publicly-available Hastebin instance. No reason why this exists.'
    url: 'https://haste.bean.codes'
    method: GET
    expectStatus: 200
    followRedirect: true
